name: blitzware_flutter_sdk
description: BlitzWare authentication SDK for Flutter applications
version: 1.0.0
homepage: https://blitzware.xyz
repository: https://github.com/LanderDK/blitzware_flutter_sdk
issue_tracker: https://github.com/LanderDK/blitzware_flutter_sdk/issues
documentation: https://docs.blitzware.xyz

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Authentication & HTTP
  http: ^1.1.0
  flutter_appauth: ^6.0.2
  flutter_secure_storage: ^9.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Utilities
  crypto: ^3.0.3
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0

flutter:
  # No assets or fonts defined